// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjlgymfnmwkysixofiol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqbGd5bWZubXdreXNpeG9maW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MzA5MTIsImV4cCI6MjA2MzIwNjkxMn0.Ba0v3FWshw1BEx_dnXpKQabZp_l9HZdQaFv4wictUwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);